repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: dfc-check
        name: df-contracts check
        entry: dfc check --contract contracts/orders.json --profile prod
        language: system
        files: "data/.*\\.(csv|parquet)$"
        pass_filenames: false
