name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[polars]
          pip install pytest pytest-cov ruff black mypy pre-commit
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Type check
        run: mypy
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Test
        run: pytest --cov=df_contracts
      - name: Generate validation artefacts
        run: |
          mkdir -p build
          dfc init tests/data/sample.csv --no-show-suggestions > build/contract.json
          dfc check tests/data/bad_sample.csv --contract build/contract.json --report build/report.json --html build/report.html --junit build/report.xml || true
        continue-on-error: true
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: dfc-reports-${{ matrix.os }}-${{ matrix.python-version }}
          path: build/
